/**
 * Copyright (C) 2011 STI Innsbruck, UIBK
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */
package at.sti2.msee.invocation.api.grounding;

import at.sti2.msee.invocation.api.grounding.exception.GroundingException;


/**
 * <b>Purpose:</b>
 * <br>
 * <b>Description:</b>
 * <br>
 * <b>Copyright:</b>     Copyright (c) 2011 STI<br>
 * <b>Company:</b>       STI Innsbruck<br>
 *
 * @author      Alex Oberhauser<br>
 * @version     $Id$<br>
 * Date of creation:  13.04.2011<br>
 * File:         $Source$<br>
 * Modifier:     $Author$<br>
 * Revision:     $Revision$<br>
 * State:        $State$<br>
 */
public interface IGroundingEngine {
	
	/**
	 * Lower rdf input data to xml data using transformations
	 * @param rdfInputData rdf triples serialized as rdfxml
	 * @return xml output generated by transformation
	 * @throws GroundingException
	 */
	public String lower(String rdfInputData) throws GroundingException;
	
	/**
	 * Lift xml input to rdf data using transformations
	 * @param xmlInputData xml input
	 * @return rdf triples serialized as rdfxml
	 * @throws GroundingException
	 */
	public String lift(String xmlInputData) throws GroundingException;
}
