source 'https://rubygems.org'

gem 'rails', '~>3.2.0'

gem "activerecord-jdbc-adapter", "~> 1.2.8"
#gem "activerecord-jdbc-adapter", "~> 1.2." #check!?
gem "activerecord-jdbcsqlite3-adapter", "~> 1.2.5"
gem "jdbc-sqlite3", "~> 3.7.2.1"
gem "activerecord-jdbcpostgresql-adapter", "~> 1.2.5"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
    # See https://github.com/sstephenson/execjs#readme for more supported runtimes
    #gem 'therubyracer'
    gem "therubyrhino", "~> 2.0.2"
    gem 'uglifier', '>= 1.0.3'
end

# Haml Support
gem "haml-rails", "~> 0.3.5"

gem "jquery-rails", "~> 2.2.0"

gem "memcache-client", "~> 1.8.5"

gem "devise", "~> 2.2.3"

gem "eventmachine", "~> 1.0.0.beta.4.1"


# Deploy with Capistrano
#gem 'rvm-capistrano'

# To use debugger
# gem 'ruby-debug'

# SOAP Library
gem "savon",  '~>1.2.0'

#XPATHp
gem "nokogiri", "~> 1.5.6"

#XML decoding
require 'cgi'

#json support
require 'pp'
gem "json", "~> 1.7.6"
gem "httparty", "~> 0.9.0"

group :development do
  gem 'warbler', '~> 1.3.6'
end
