
package at.sti2.ngsee.invoker_webservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.0
 * Thu Mar 17 22:49:10 CET 2011
 * Generated source version: 2.3.0
 * 
 */
 
public class InvokerWebService_PortTypeServer{

    protected InvokerWebService_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new at.sti2.ngsee.invoker_webservice.InvokerWebService();
        String address = "http://localhost:9090/InvokerWebServicePort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new InvokerWebService_PortTypeServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 