
package at.sti2.wsmf.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EventStreamWebService", targetNamespace = "http://webservice.wsmf.sti2.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EventStreamWebService {


    /**
     * 
     * @param soapaction
     * @param method
     * @param endpoint
     * @param namespace
     */
    @WebMethod
    @RequestWrapper(localName = "subscribeStateChannel", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.SubscribeStateChannel")
    @ResponseWrapper(localName = "subscribeStateChannelResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.SubscribeStateChannelResponse")
    public void subscribeStateChannel(
        @WebParam(name = "endpoint", targetNamespace = "")
        String endpoint,
        @WebParam(name = "namespace", targetNamespace = "")
        String namespace,
        @WebParam(name = "method", targetNamespace = "")
        String method,
        @WebParam(name = "soapaction", targetNamespace = "")
        String soapaction);

    /**
     * 
     * @param endpoint
     */
    @WebMethod
    @RequestWrapper(localName = "unsubscribeAvailabilityChannel", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.UnsubscribeAvailabilityChannel")
    @ResponseWrapper(localName = "unsubscribeAvailabilityChannelResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.UnsubscribeAvailabilityChannelResponse")
    public void unsubscribeAvailabilityChannel(
        @WebParam(name = "endpoint", targetNamespace = "")
        String endpoint);

    /**
     * 
     * @param soapaction
     * @param method
     * @param endpoint
     * @param namespace
     */
    @WebMethod
    @RequestWrapper(localName = "subscribeAvailabilityChannel", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.SubscribeAvailabilityChannel")
    @ResponseWrapper(localName = "subscribeAvailabilityChannelResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.SubscribeAvailabilityChannelResponse")
    public void subscribeAvailabilityChannel(
        @WebParam(name = "endpoint", targetNamespace = "")
        String endpoint,
        @WebParam(name = "namespace", targetNamespace = "")
        String namespace,
        @WebParam(name = "method", targetNamespace = "")
        String method,
        @WebParam(name = "soapaction", targetNamespace = "")
        String soapaction);

    /**
     * 
     * @param soapaction
     * @param method
     * @param endpoint
     * @param namespace
     */
    @WebMethod
    @RequestWrapper(localName = "subscribeQoSChannel", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.SubscribeQoSChannel")
    @ResponseWrapper(localName = "subscribeQoSChannelResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.SubscribeQoSChannelResponse")
    public void subscribeQoSChannel(
        @WebParam(name = "endpoint", targetNamespace = "")
        String endpoint,
        @WebParam(name = "namespace", targetNamespace = "")
        String namespace,
        @WebParam(name = "method", targetNamespace = "")
        String method,
        @WebParam(name = "soapaction", targetNamespace = "")
        String soapaction);

    /**
     * 
     * @param endpoint
     */
    @WebMethod
    @RequestWrapper(localName = "unsubscribeStateChannel", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.UnsubscribeStateChannel")
    @ResponseWrapper(localName = "unsubscribeStateChannelResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.UnsubscribeStateChannelResponse")
    public void unsubscribeStateChannel(
        @WebParam(name = "endpoint", targetNamespace = "")
        String endpoint);

    /**
     * 
     * @param endpoint
     */
    @WebMethod
    @RequestWrapper(localName = "unsubscribeQoSChannel", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.UnsubscribeQoSChannel")
    @ResponseWrapper(localName = "unsubscribeQoSChannelResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.UnsubscribeQoSChannelResponse")
    public void unsubscribeQoSChannel(
        @WebParam(name = "endpoint", targetNamespace = "")
        String endpoint);

}
