
package at.sti2.wsmf.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ManagementWebService", targetNamespace = "http://webservice.wsmf.sti2.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManagementWebService {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listEndpoints", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.ListEndpoints")
    @ResponseWrapper(localName = "listEndpointsResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.ListEndpointsResponse")
    public List<String> listEndpoints();

    /**
     * 
     * @param value
     * @param endpoint
     */
    @WebMethod
    @RequestWrapper(localName = "changeQoSThresholdValue", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.ChangeQoSThresholdValue")
    @ResponseWrapper(localName = "changeQoSThresholdValueResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.ChangeQoSThresholdValueResponse")
    public void changeQoSThresholdValue(
        @WebParam(name = "endpoint", targetNamespace = "")
        String endpoint,
        @WebParam(name = "value", targetNamespace = "")
        QoSThresholdValue value);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listInstanceIDs", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.ListInstanceIDs")
    @ResponseWrapper(localName = "listInstanceIDsResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.ListInstanceIDsResponse")
    public List<String> listInstanceIDs();

    /**
     * 
     * @param endpoint
     */
    @WebMethod
    @RequestWrapper(localName = "removeEndpoint", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.RemoveEndpoint")
    @ResponseWrapper(localName = "removeEndpointResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.RemoveEndpointResponse")
    public void removeEndpoint(
        @WebParam(name = "endpoint", targetNamespace = "")
        String endpoint);

    /**
     * 
     * @param endpoint
     */
    @WebMethod
    @RequestWrapper(localName = "addEndpoint", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.AddEndpoint")
    @ResponseWrapper(localName = "addEndpointResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.AddEndpointResponse")
    public void addEndpoint(
        @WebParam(name = "endpoint", targetNamespace = "")
        String endpoint);

    /**
     * 
     * @param key
     * @param endpoint
     * @return
     *     returns at.sti2.wsmf.webservice.QoSThresholdValue
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQoSThresholdValue", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.GetQoSThresholdValue")
    @ResponseWrapper(localName = "getQoSThresholdValueResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.GetQoSThresholdValueResponse")
    public QoSThresholdValue getQoSThresholdValue(
        @WebParam(name = "endpoint", targetNamespace = "")
        String endpoint,
        @WebParam(name = "key", targetNamespace = "")
        QoSThresholdKey key);

    /**
     * 
     * @param key
     * @param endpoint
     * @return
     *     returns at.sti2.wsmf.webservice.QoSParamValue
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQoSParam", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.GetQoSParam")
    @ResponseWrapper(localName = "getQoSParamResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.GetQoSParamResponse")
    public QoSParamValue getQoSParam(
        @WebParam(name = "endpoint", targetNamespace = "")
        String endpoint,
        @WebParam(name = "key", targetNamespace = "")
        QoSParamKey key);

    /**
     * 
     * @param activityStartedEvent
     * @return
     *     returns at.sti2.wsmf.webservice.WsInvocationState
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInvocationState", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.GetInvocationState")
    @ResponseWrapper(localName = "getInvocationStateResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.GetInvocationStateResponse")
    public WsInvocationState getInvocationState(
        @WebParam(name = "activityStartedEvent", targetNamespace = "")
        String activityStartedEvent);

}
