
package at.sti2.wsmf.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProxyWebServiceService", targetNamespace = "http://webservice.wsmf.sti2.at/", wsdlLocation = "http://localhost:9090/wsmf-webservice/services/proxy?wsdl")
public class ProxyWebServiceService
    extends Service
{

    private final static URL PROXYWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(at.sti2.wsmf.webservice.ProxyWebServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = at.sti2.wsmf.webservice.ProxyWebServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9090/wsmf-webservice/services/proxy?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9090/wsmf-webservice/services/proxy?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROXYWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public ProxyWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProxyWebServiceService() {
        super(PROXYWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://webservice.wsmf.sti2.at/", "ProxyWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns ProxyWebService
     */
    @WebEndpoint(name = "ProxyWebServicePort")
    public ProxyWebService getProxyWebServicePort() {
        return super.getPort(new QName("http://webservice.wsmf.sti2.at/", "ProxyWebServicePort"), ProxyWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProxyWebService
     */
    @WebEndpoint(name = "ProxyWebServicePort")
    public ProxyWebService getProxyWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.wsmf.sti2.at/", "ProxyWebServicePort"), ProxyWebService.class, features);
    }

}
