
package at.sti2.wsmf.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProxyWebService", targetNamespace = "http://webservice.wsmf.sti2.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProxyWebService {


    /**
     * 
     * @param soapAction
     * @param soapRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "invoke", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.Invoke")
    @ResponseWrapper(localName = "invokeResponse", targetNamespace = "http://webservice.wsmf.sti2.at/", className = "at.sti2.wsmf.webservice.InvokeResponse")
    public String invoke(
        @WebParam(name = "soapRequest", targetNamespace = "")
        String soapRequest,
        @WebParam(name = "soapAction", targetNamespace = "")
        String soapAction);

}
