<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="RandomNumberWebServiceService" targetNamespace="http://sesa.sti2.at/services/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://sesa.sti2.at/services/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<xs:schema elementFormDefault="unqualified" targetNamespace="http://sesa.sti2.at/services/" version="1.0" xmlns:tns="http://sesa.sti2.at/services/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="getRandomNumberAndCalculationTime" type="tns:getRandomNumberAndCalculationTime"/>
<xs:element name="getRandomNumberAndCalculationTimeResponse" type="tns:getRandomNumberAndCalculationTimeResponse"/>
<xs:complexType name="getRandomNumberAndCalculationTime">
    <xs:sequence>
      <xs:element name="number" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="getRandomNumberAndCalculationTimeResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="RandomNumberResponse" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="getRandomNumberAndCalculationTimeResponse">
    <wsdl:part element="tns:getRandomNumberAndCalculationTimeResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getRandomNumberAndCalculationTime">
    <wsdl:part element="tns:getRandomNumberAndCalculationTime" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="RandomNumberWebService">
    <wsdl:operation name="getRandomNumberAndCalculationTime">
      <wsdl:input message="tns:getRandomNumberAndCalculationTime" name="getRandomNumberAndCalculationTime">
    </wsdl:input>
      <wsdl:output message="tns:getRandomNumberAndCalculationTimeResponse" name="getRandomNumberAndCalculationTimeResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RandomNumberWebServiceServiceSoapBinding" type="tns:RandomNumberWebService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getRandomNumberAndCalculationTime">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getRandomNumberAndCalculationTime">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getRandomNumberAndCalculationTimeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RandomNumberWebServiceService">
    <wsdl:port binding="tns:RandomNumberWebServiceServiceSoapBinding" name="RandomNumberWebServicePort">
      <soap:address location="http://localhost:9292/at.sti2.msee.testwebservices/services/randomnumber"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>