package at.sti2.msee.delivery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-29T15:13:00.784+01:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://msee.sti2.at/delivery/", name = "RegistrationServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface RegistrationServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://msee.sti2.at/delivery/", className = "at.sti2.msee.delivery.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://msee.sti2.at/delivery/", className = "at.sti2.msee.delivery.UpdateResponse")
    public java.lang.String update(
        @WebParam(name = "serviceURI", targetNamespace = "")
        java.lang.String serviceURI,
        @WebParam(name = "serviceURL", targetNamespace = "")
        java.lang.String serviceURL
    ) throws ServiceRegistrationException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://msee.sti2.at/delivery/", className = "at.sti2.msee.delivery.Register")
    @WebMethod
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://msee.sti2.at/delivery/", className = "at.sti2.msee.delivery.RegisterResponse")
    public java.lang.String register(
        @WebParam(name = "serviceDescriptionURL", targetNamespace = "")
        java.lang.String serviceDescriptionURL
    ) throws ServiceRegistrationException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registerInContext", targetNamespace = "http://msee.sti2.at/delivery/", className = "at.sti2.msee.delivery.RegisterInContext")
    @WebMethod
    @ResponseWrapper(localName = "registerInContextResponse", targetNamespace = "http://msee.sti2.at/delivery/", className = "at.sti2.msee.delivery.RegisterInContextResponse")
    public java.lang.String registerInContext(
        @WebParam(name = "serviceDescriptionURL", targetNamespace = "")
        java.lang.String serviceDescriptionURL,
        @WebParam(name = "contextURI", targetNamespace = "")
        java.lang.String contextURI
    ) throws ServiceRegistrationException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deregister", targetNamespace = "http://msee.sti2.at/delivery/", className = "at.sti2.msee.delivery.Deregister")
    @WebMethod
    @ResponseWrapper(localName = "deregisterResponse", targetNamespace = "http://msee.sti2.at/delivery/", className = "at.sti2.msee.delivery.DeregisterResponse")
    public java.lang.String deregister(
        @WebParam(name = "serviceURI", targetNamespace = "")
        java.lang.String serviceURI
    ) throws ServiceRegistrationException_Exception;
}
