
package at.sti2.msee.delivery;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-29T15:13:00.773+01:00
 * Generated source version: 2.7.3
 */

@WebFault(name = "ServiceRegistrationException", targetNamespace = "http://msee.sti2.at/delivery/")
public class ServiceRegistrationException_Exception extends Exception {
    
    private at.sti2.msee.delivery.ServiceRegistrationException serviceRegistrationException;

    public ServiceRegistrationException_Exception() {
        super();
    }
    
    public ServiceRegistrationException_Exception(String message) {
        super(message);
    }
    
    public ServiceRegistrationException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceRegistrationException_Exception(String message, at.sti2.msee.delivery.ServiceRegistrationException serviceRegistrationException) {
        super(message);
        this.serviceRegistrationException = serviceRegistrationException;
    }

    public ServiceRegistrationException_Exception(String message, at.sti2.msee.delivery.ServiceRegistrationException serviceRegistrationException, Throwable cause) {
        super(message, cause);
        this.serviceRegistrationException = serviceRegistrationException;
    }

    public at.sti2.msee.delivery.ServiceRegistrationException getFaultInfo() {
        return this.serviceRegistrationException;
    }
}
