package at.sti2.msee.delivery;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-29T15:13:00.797+01:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "ServiceRegistrationService", 
                  wsdlLocation = "file:/home/ikelar/Dropbox/STI/Workspaces/msee-sdp/msee-core/registration/webservice/target/../src/main/resources/RegistrationAPI.wsdl",
                  targetNamespace = "http://msee.sti2.at/delivery/") 
public class ServiceRegistrationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://msee.sti2.at/delivery/", "ServiceRegistrationService");
    public final static QName RegistrationServicePortTypePort = new QName("http://msee.sti2.at/delivery/", "RegistrationServicePortTypePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/ikelar/Dropbox/STI/Workspaces/msee-sdp/msee-core/registration/webservice/target/../src/main/resources/RegistrationAPI.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceRegistrationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/ikelar/Dropbox/STI/Workspaces/msee-sdp/msee-core/registration/webservice/target/../src/main/resources/RegistrationAPI.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceRegistrationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceRegistrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceRegistrationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceRegistrationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceRegistrationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceRegistrationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RegistrationServicePortType
     */
    @WebEndpoint(name = "RegistrationServicePortTypePort")
    public RegistrationServicePortType getRegistrationServicePortTypePort() {
        return super.getPort(RegistrationServicePortTypePort, RegistrationServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrationServicePortType
     */
    @WebEndpoint(name = "RegistrationServicePortTypePort")
    public RegistrationServicePortType getRegistrationServicePortTypePort(WebServiceFeature... features) {
        return super.getPort(RegistrationServicePortTypePort, RegistrationServicePortType.class, features);
    }

}
