
package at.sti2.msee.delivery;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ServiceRegistrationException", targetNamespace = "http://msee.sti2.at/delivery/registration/")
public class ServiceRegistrationException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private at.sti2.msee.delivery.registration.ServiceRegistrationException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServiceRegistrationException(String message, at.sti2.msee.delivery.registration.ServiceRegistrationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServiceRegistrationException(String message, at.sti2.msee.delivery.registration.ServiceRegistrationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: at.sti2.msee.delivery.registration.ServiceRegistrationException
     */
    public at.sti2.msee.delivery.registration.ServiceRegistrationException getFaultInfo() {
        return faultInfo;
    }

}
