package at.sti2.ngsee.invoker.api.grounding;

import at.sti2.ngsee.invoker.api.grounding.exception.GroundingException;


/**
 * <b>Purpose:</b>
 * <br>
 * <b>Description:</b>
 * <br>
 * <b>Copyright:</b>     Copyright (c) 2011 STI<br>
 * <b>Company:</b>       STI Innsbruck<br>
 *
 * @author      Alex Oberhauser<br>
 * @version     $Id$<br>
 * Date of creation:  13.04.2011<br>
 * File:         $Source$<br>
 * Modifier:     $Author$<br>
 * Revision:     $Revision$<br>
 * State:        $State$<br>
 */
public interface IGroundingEngine {
	
	/**
	 * Lower rdf input data to xml data using transformations
	 * @param rdfInputData rdf triples serialized as rdfxml
	 * @return xml output generated by transformation
	 * @throws GroundingException
	 */
	public String lower(String rdfInputData) throws GroundingException;
	
	/**
	 * Lift xml input to rdf data using transformations
	 * @param xmlInputData xml input
	 * @return rdf triples serialized as rdfxml
	 * @throws GroundingException
	 */
	public String lift(String xmlInputData) throws GroundingException;
}
